//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Niqash.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Niqash.Resources.ViewsResource", typeof(ViewsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write something about yourself ..........
        /// </summary>
        public static string aboutMePlaceholder {
            get {
                return ResourceManager.GetString("aboutMePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niqash is a social network to share and discuss any subject and any time with big socity from all the world..
        /// </summary>
        public static string aboutSitePargraph {
            get {
                return ResourceManager.GetString("aboutSitePargraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can add your ad here just connect with us..
        /// </summary>
        public static string adDescription {
            get {
                return ResourceManager.GetString("adDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        public static string allUsers {
            get {
                return ResourceManager.GetString("allUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niqash.
        /// </summary>
        public static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile Picture.
        /// </summary>
        public static string changeProfilePic {
            get {
                return ResourceManager.GetString("changeProfilePic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string comment {
            get {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string confirmEmail {
            get {
                return ResourceManager.GetString("confirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string confirmEmailMsg {
            get {
                return ResourceManager.GetString("confirmEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string editProfile {
            get {
                return ResourceManager.GetString("editProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit your profile .
        /// </summary>
        public static string editProfileIntro {
            get {
                return ResourceManager.GetString("editProfileIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string erorr {
            get {
                return ResourceManager.GetString("erorr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is a problem try again please.
        /// </summary>
        public static string erorrMsg {
            get {
                return ResourceManager.GetString("erorrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow.
        /// </summary>
        public static string follow {
            get {
                return ResourceManager.GetString("follow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string followers {
            get {
                return ResourceManager.GetString("followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string following {
            get {
                return ResourceManager.GetString("following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string forgotPassword {
            get {
                return ResourceManager.GetString("forgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password Confirmation.
        /// </summary>
        public static string forgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("forgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we send to your email a link to reset your password Please check your email .
        /// </summary>
        public static string forgotPasswordConfirmationMsg {
            get {
                return ResourceManager.GetString("forgotPasswordConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string getStarted {
            get {
                return ResourceManager.GetString("getStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global.
        /// </summary>
        public static string global {
            get {
                return ResourceManager.GetString("global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account.
        /// </summary>
        public static string haveAccountMsg {
            get {
                return ResourceManager.GetString("haveAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string haveNoAccountMsg {
            get {
                return ResourceManager.GetString("haveNoAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to like.
        /// </summary>
        public static string like {
            get {
                return ResourceManager.GetString("like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email or password is incorrect, try again.
        /// </summary>
        public static string loginErorrMsg {
            get {
                return ResourceManager.GetString("loginErorrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with your email.
        /// </summary>
        public static string loginMsg {
            get {
                return ResourceManager.GetString("loginMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Out.
        /// </summary>
        public static string loginOut {
            get {
                return ResourceManager.GetString("loginOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to love.
        /// </summary>
        public static string love {
            get {
                return ResourceManager.GetString("love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string myAccount {
            get {
                return ResourceManager.GetString("myAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new account.
        /// </summary>
        public static string newAccountMsg {
            get {
                return ResourceManager.GetString("newAccountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add useful comment.
        /// </summary>
        public static string newCommentPlaceholder {
            get {
                return ResourceManager.GetString("newCommentPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share some thing useful.
        /// </summary>
        public static string newPostPlaceholder {
            get {
                return ResourceManager.GetString("newPostPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OH, sorry we dont find any comment Belongs to this post, try to add one.
        /// </summary>
        public static string noCommentsMsg {
            get {
                return ResourceManager.GetString("noCommentsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there is no one  follow this user, yet.
        /// </summary>
        public static string nofollowersMsg {
            get {
                return ResourceManager.GetString("nofollowersMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this user does not follow any users.
        /// </summary>
        public static string nofollowingMsg {
            get {
                return ResourceManager.GetString("nofollowingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OH, sorry we dont find any post Belongs to you or your friends, try to add one.
        /// </summary>
        public static string noPostsMsg {
            get {
                return ResourceManager.GetString("noPostsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we don`t found any user starts with this Letter.
        /// </summary>
        public static string noSearchResult {
            get {
                return ResourceManager.GetString("noSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string posts {
            get {
                return ResourceManager.GetString("posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to React.
        /// </summary>
        public static string react {
            get {
                return ResourceManager.GetString("react", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure you want delete this Comment.
        /// </summary>
        public static string removeCommentWarningMsg {
            get {
                return ResourceManager.GetString("removeCommentWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure you want delete this Post.
        /// </summary>
        public static string removePostWarningMsg {
            get {
                return ResourceManager.GetString("removePostWarningMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string resetPassword {
            get {
                return ResourceManager.GetString("resetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Confirmation.
        /// </summary>
        public static string resetPasswordConfirmation {
            get {
                return ResourceManager.GetString("resetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset. Please .
        /// </summary>
        public static string resetPasswordConfirmationMsg {
            get {
                return ResourceManager.GetString("resetPasswordConfirmationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string resetPasswordMsg {
            get {
                return ResourceManager.GetString("resetPasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        public static string searchResult {
            get {
                return ResourceManager.GetString("searchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry you should write one Letter at least.
        /// </summary>
        public static string searchValidation {
            get {
                return ResourceManager.GetString("searchValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Email.
        /// </summary>
        public static string sendEmail {
            get {
                return ResourceManager.GetString("sendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string share {
            get {
                return ResourceManager.GetString("share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should confirm your email, to be able to reset account password.
        /// </summary>
        public static string shouldConfirmEmailMsg {
            get {
                return ResourceManager.GetString("shouldConfirmEmailMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we have......
        /// </summary>
        public static string siteStatisticsHeading {
            get {
                return ResourceManager.GetString("siteStatisticsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success !.
        /// </summary>
        public static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed.
        /// </summary>
        public static string successChangePasswordMsg {
            get {
                return ResourceManager.GetString("successChangePasswordMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your Profile Picture was updated.
        /// </summary>
        public static string successChangeProfilePicMsg {
            get {
                return ResourceManager.GetString("successChangeProfilePicMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your account was updated.
        /// </summary>
        public static string successEditProfileMsg {
            get {
                return ResourceManager.GetString("successEditProfileMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Follow.
        /// </summary>
        public static string unFollow {
            get {
                return ResourceManager.GetString("unFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Comment.
        /// </summary>
        public static string updateComment {
            get {
                return ResourceManager.GetString("updateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Post.
        /// </summary>
        public static string updatePost {
            get {
                return ResourceManager.GetString("updatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string user {
            get {
                return ResourceManager.GetString("user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Message.
        /// </summary>
        public static string warningMsg {
            get {
                return ResourceManager.GetString("warningMsg", resourceCulture);
            }
        }
    }
}
